train:
    batch_size: 8
    validation_split: 1
    num_epochs: 200
    learning_rate: 0.0001
    weight_decay: 0.0001

model:
  input_size: 256
  layers_num: 7
  layers_width: 32
  iterations_num: 8
